apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: {{index . "namespace"}}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{index . "AWS_ACCESS_KEY_ID"}}
  AWS_SECRET_ACCESS_KEY: {{index . "AWS_SECRET_ACCESS_KEY"}}
